### PR TITLE
Apply using stored documents. #27

### PR DESCRIPTION
**Pull request by OussamaJmili**
#27
* Added the possibility to choose the stored resume or the stored cover letter to apply with
* the user can see his stored docs before applying

### CODE REVIEW

**Review by nicotowa — APPROVED** [review]
PR approved

**Review by drbladz — COMMENTED** [review]
Do you still need the commented code? If not, try to remove unnecessary code the most you can for best practices.

**Comment by OussamaJmili** [comment]
@drbladz Will do in a later pull request, I'm trying to keep track of some changes I made

**Review by drbladz — APPROVED** [review]
Alright, sounds good.

**Pull request merged**
